version: "3.3"
services:
  neofura_http:
    build:
      context: "./neo3fura_http"
      args:
        RT: ${RUNTIME}
    ports:
      - "1926:1926"
    networks:
      - network
    restart: always
    container_name: service_http_${RUNTIME}
    depends_on:
      - redis
      - mongo

  neofura_ws:
    build:
      context: "./neo3fura_ws"
      args:
        RT: ${RUNTIME}
    ports:
      - "2026:2026"
    networks:
      - network
    restart: always
    container_name: service_ws_${RUNTIME}
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    networks:
      - network
    ports:
      - "6379:6379"
    container_name: cache_${RUNTIME}

  mongo:
    image: mongo
    restart: always
    container_name: mongo_${RUNTIME}
    networks:
      - network
    ports:
      - "27001:27017"
    expose:
      - "27017"

networks:
  network:
